# Generated by Django 6.0.6 on 2026-06-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('taken_at', models.DateTimeField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.observation')),
            ],
        ),
    ]
