# Generated by Django 6.0.6 on 2026-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_observation_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('supported', 'Supported'), ('refuted', 'Refuted'), ('inconclusive', 'Inconclusive')], default='open', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='hypotheses',
            field=models.ManyToManyField(to='main_app.hypothesis'),
        ),
    ]
